name: Build and test
on:
  workflow_dispatch:
  pull_request:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: cache-gradle-and-deps-${{ hashFiles('**/*gradle*') }}

      - name: Build project
        run: ./gradlew build --stacktrace

      - name: run JVM tests
        run: ./gradlew jvmTest --stacktrace

      - name: run JS tests
        run: ./gradlew jsTest --stacktrace

# # XXX: disabling native targets because they still cause trouble on apple M1 in kotlin 1.6.10
#      - name: run native tests
#        run: ./gradlew nativeTest --stacktrace
